spring:
  application:
    name: edge-dematic
  jackson:
    default-property-inclusion: non_null
  liquibase:
    enabled: false

feign:
  client:
    config:
      default:
        loggerLevel: full

logging:
  level:
    org:
      springframework:
        cache: OFF

server.port: 8081
folio.tenant.validation.enabled: false
